### ISSUE TITLE
! LaTeX Error: File `tkz-graph.sty' not found.

### ISSUE THREAD

**Issue by lkp520** [iagoac/elsevier#1]
! LaTeX Error: File `tkz-graph.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:

**Comment by ScottTylerHall349** [comment]
@lkp520 worth [noting](https://www.overleaf.com/blog/tex-live-2020-now-available):
![image](https://user-images.githubusercontent.com/46343472/137531710-5574bc38-9e61-48a8-bb7e-115eb1c77971.png)

**Comment by iagoac** [comment]
Thank both of you for pointing out this issue.  
I will handle it ASAP

**Comment by iagoac** [comment]
File inserted as requested
