### ISSUE TITLE
affiliation is broken in this code 

### ISSUE THREAD

**Issue by vijaypanchalr3** [iagoac/elsevier#3]
there's not command as affiliation

**Comment by iagoac** [comment]
@vijaypanchalr3 please can you elaborate on this issue?

To the best of my knowledge, the affiliation is inserted using the `\address` command along with the token inserted in the `\author`.

For example, for the author `\author[label2]{Homer J. Simpson}`, the affiliation is given in `\address[label2]{Twenty Century Fox, USA}`
